#!/usr/bin/env bash
# Transfer a file to a remote server
# File_path, server IP, username and identity file passed
#  on the commandline

if [ !$4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	sed -i 's/StrictHostKeyChecking\s[a,y,n][s,e,o][k,s]/StrictHostKeyChecking no/g' /etc/ssh/ssh_config
	scp $1 scp://$3@$2/~/ -i $4
fi
