#!/usr/bin/env bash
# This script installs nginx on the computer it's run on.
#  It prints 'Hello world' when curled
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
