#!/usr/bin/env bash
# Configure nginx to redirect calls to /redirect to another page
sudo apt-get -y update
sudo apt-get install nginx -y

echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '/^\tserver_name_.*/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
service nginx restart
