#!/usr/bin/env bash
# Configure nginx to generate a custom 404 Error message
sudo apt-get -y update
sudo apt-get install nginx -y

echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '/^\tserver_name_.*/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/^\tserver_name_.*/a \\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
service nginx restart
