#!/usr/bin/env bash
# This script sets up a brand new ubuntu machine to install nginx
#	and configure it to return an extra header
#
# Step 1: updating the apt package list
apt-get update

# step 2: installing the nginx
sudo apt-get install nginx -y

# step3: allow connections connecting to port 80
ufw allow 80/http

#step 4: configure nginx to return a header telling hostname of the server
host=$(hostname)
sed -i "/^http.*/a \\\tadd_header X-Served-By $host;" /etc/nginx/nginx.conf

#step 5: restart nginx server
service nginx restart
