#!/usr/bin/env bash
#Create a script that handles different signals
echo $$ >> /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I hate the kill command; rm -rf /var/run/myscript.pid; exit" SIGTERM
	trap "echo Y U no lobe me?!" SIGINT
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
done
