#!/usr/bin/env bash
#Manage the manage_my_process like the init.d manage background processes
case $1 in
	"start")
		./manage_my_process &
		touch /var/run/my_process.pid
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started";;
	"stop")
		kill -SIGTERM $(cat /var/run/my_process.pid)
		rm -rf /var/run/my_process.pid
		echo "manage_my_process stopped";;
	"restart")
		kill -SIGTERM $(cat /var/run/my_process.pid)
		rm -rf /var/run/my_process.pid
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted";;
	*)
		echo "Usage: manage_my_process {start|stop|restart}";;
esac
